Import Libraries

In [1]:
import csv
import numpy as np
import tensorflow as tf


  TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0.

  Please upgrade your code to TensorFlow 2.0:
    * https://www.tensorflow.org/beta/guide/migration_guide

  Or install the latest stable TensorFlow 1.X release:
    * `pip install -U "tensorflow==1.*"`

  Otherwise your code may be broken by the change.

  


In [2]:
attack_set_1_raw = np.genfromtxt('set2_attack_udp_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

attack_set_2_raw = np.genfromtxt('set2_attack2_udp_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

no_attack_set_1_raw = np.genfromtxt('set2_no_attack_udp_none_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

no_attack_set_2_raw = np.genfromtxt('set2_no_attack2_udp_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

OSError: set2_attack_udp_zodiac.csv not found.

In [ ]:
attack_set_1 = np.delete(attack_set_1_raw, 2, axis=1)
attack_set_2 = np.delete(attack_set_2_raw, 2, axis=1)
no_attack_set_1 = np.delete(no_attack_set_1_raw, 2, axis=1)
no_attack_set_2 = np.delete(no_attack_set_2_raw, 2, axis=1)

'''
attack_set_1 = np.delete(attack_set_1, 2, axis=1)
attack_set_2 = np.delete(attack_set_2, 2, axis=1)
no_attack_set_1 = np.delete(no_attack_set_1, 2, axis=1)
no_attack_set_2 = np.delete(no_attack_set_2, 2, axis=1)

attack_set_1 = np.delete(attack_set_1, 2, axis=1)
attack_set_2 = np.delete(attack_set_2, 2, axis=1)
no_attack_set_1 = np.delete(no_attack_set_1, 2, axis=1)
no_attack_set_2 = np.delete(no_attack_set_2, 2, axis=1)
'''

In [4]:
zeroes_set = np.zeros((len(attack_set_1),1))
ones_set = np.ones((len(no_attack_set_1),1))

In [5]:
training_set = np.concatenate((attack_set_1,no_attack_set_1,no_attack_set_2), axis=0) 
training_targets = np.concatenate((ones_set, zeroes_set, zeroes_set), axis=0)

In [21]:
training_set

array([[2.44470000e+04, 1.26024629e+08, 1.00103371e+01, 0.00000000e+00],
       [2.09880000e+04, 1.21181628e+08, 1.00102270e+01, 0.00000000e+00],
       [2.10620000e+04, 1.21288168e+08, 1.00103872e+01, 0.00000000e+00],
       ...,
       [8.95500000e+03, 1.25412570e+07, 1.00103660e+01, 0.00000000e+00],
       [1.19600000e+04, 1.67505960e+07, 1.30243621e+01, 2.00000000e+00],
       [9.16500000e+03, 1.28287540e+07, 1.00103278e+01, 0.00000000e+00]])

In [6]:
training_set_standardized = tf.keras.utils.normalize(
    training_set,
    axis = -1,
    order = 2
)

In [7]:
input_size = 4
output_size = 1

model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation='relu', input_shape=(input_size,)),
    tf.keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.00001), 
                loss='binary_crossentropy', 
                metrics=['accuracy'])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [8]:
model.fit(training_set, training_targets, epochs=300, verbose=1)

Train on 357 samples
Epoch 1/300
357/357 [==============================] - 0s 455us/sample - loss: 150951.9179 - acc: 0.4482
Epoch 2/300
357/357 [==============================] - 0s 106us/sample - loss: 93233.4969 - acc: 0.4482
Epoch 3/300
357/357 [==============================] - 0s 88us/sample - loss: 36633.7600 - acc: 0.4482
Epoch 4/300
357/357 [==============================] - 0s 126us/sample - loss: 1712.7373 - acc: 0.4006
Epoch 5/300
357/357 [==============================] - 0s 109us/sample - loss: 3194.4604 - acc: 0.3557
Epoch 6/300
357/357 [==============================] - 0s 168us/sample - loss: 3245.7095 - acc: 0.3557
Epoch 7/300
357/357 [==============================] - 0s 145us/sample - loss: 2597.2154 - acc: 0.3557
Epoch 8/300
357/357 [==============================] - 0s 107us/sample - loss: 1659.6535 - acc: 0.4258
Epoch 9/300
357/357 [==============================] - 0s 138us/sample - loss: 556.7094 - acc: 0.4538
Epoch 10/300
357/357 [============================

357/357 [==============================] - 0s 85us/sample - loss: 0.1053 - acc: 1.0000
Epoch 163/300
357/357 [==============================] - 0s 85us/sample - loss: 0.1046 - acc: 1.0000
Epoch 164/300
357/357 [==============================] - 0s 79us/sample - loss: 0.1040 - acc: 1.0000
Epoch 165/300
357/357 [==============================] - 0s 62us/sample - loss: 0.1034 - acc: 1.0000
Epoch 166/300
357/357 [==============================] - 0s 85us/sample - loss: 0.1027 - acc: 1.0000
Epoch 167/300
357/357 [==============================] - 0s 113us/sample - loss: 0.1021 - acc: 1.0000
Epoch 168/300
357/357 [==============================] - 0s 85us/sample - loss: 0.1015 - acc: 1.0000
Epoch 169/300
357/357 [==============================] - 0s 85us/sample - loss: 0.1009 - acc: 1.0000
Epoch 170/300
357/357 [==============================] - 0s 51us/sample - loss: 0.1003 - acc: 1.0000
Epoch 171/300
357/357 [==============================] - 0s 116us/sample - loss: 0.0997 - acc: 1.0000
Ep

In [9]:
model.layers[0].get_weights()[1]

array([ 0.02230451, -0.0219545 ,  0.02230299, -0.02218401, -0.02362583,
        0.        , -0.02230149,  0.        ,  0.02230301,  0.        ,
        0.        , -0.02230111,  0.        ,  0.        ,  0.01525921,
        0.02230324, -0.01526081,  0.02230476,  0.02866562,  0.02230445,
        0.02547196,  0.01525899, -0.01526066,  0.02679703,  0.        ,
       -0.01501888,  0.0257307 , -0.02247812, -0.02230122,  0.        ,
        0.02230299,  0.02230295,  0.01525861,  0.        , -0.01528071,
       -0.02230123,  0.02230411,  0.02623801,  0.01525394,  0.02782579,
       -0.015261  ,  0.        ,  0.01516758,  0.0252851 ,  0.        ,
        0.        ,  0.01525773, -0.01399557,  0.        ,  0.01525919,
       -0.02383111, -0.02362276, -0.02370894,  0.        ,  0.01525934,
        0.02550788,  0.01525951, -0.01956817,  0.02230306,  0.01523943,
       -0.02230113, -0.02281268,  0.02559989,  0.        , -0.02230114,
        0.        , -0.02061267, -0.01526076,  0.        ,  0.  

In [10]:
attack_set_2_standardized = tf.keras.utils.normalize(
    attack_set_2,
    axis = -1,
    order = 2
)

In [11]:
model.predict(attack_set_1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [12]:
model.predict(attack_set_2)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [13]:
no_attack_set_2_standardized = tf.keras.utils.normalize(
    no_attack_set_2,
    axis = -1,
    order = 2
)

In [14]:
model.predict(no_attack_set_1)

array([[0.18081465],
       [0.1213873 ],
       [0.18399736],
       [0.1854757 ],
       [0.18081534],
       [0.12143421],
       [0.18081534],
       [0.12138712],
       [0.12138721],
       [0.1214743 ],
       [0.1070165 ],
       [0.12150076],
       [0.18094471],
       [0.12151212],
       [0.12154084],
       [0.12150216],
       [0.18081471],
       [0.12138712],
       [0.1213873 ],
       [0.18081588],
       [0.1213873 ],
       [0.12138712],
       [0.10695359],
       [0.1213873 ],
       [0.1213873 ],
       [0.18081418],
       [0.1213873 ],
       [0.12138712],
       [0.10695836],
       [0.12138712],
       [0.1069569 ],
       [0.12139261],
       [0.12149328],
       [0.12147614],
       [0.18081588],
       [0.12138712],
       [0.12138718],
       [0.18081465],
       [0.1213873 ],
       [0.12138712],
       [0.10695782],
       [0.06719202],
       [0.12138718],
       [0.18099648],
       [0.12138709],
       [0.12138677],
       [0.18081418],
       [0.121

In [15]:
model.predict(no_attack_set_2)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [17]:
model.save('my_model.h5')

In [20]:
model = tf.keras.models.load_model('my_model.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [23]:
model.predict([[1,1,1,1]])

ValueError: Error when checking input: expected dense_input to have shape (4,) but got array with shape (1,)