Import Libraries

In [2]:
import csv
import numpy as np
import tensorflow as tf

In [3]:
attack_set_1_raw = np.genfromtxt('attack_udp_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

attack_set_2_raw = np.genfromtxt('attack_udp2_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

no_attack_set_1_raw = np.genfromtxt('no_attack_udp_none_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

no_attack_set_2_raw = np.genfromtxt('no_attack_udp_zodiac.csv', 
                             delimiter=',',
                             skip_header=2)

In [26]:
attack_set_1 = np.take(attack_set_1_raw, [2,4,15], axis=1)
attack_set_2 = np.take(attack_set_2_raw, [2,4,15], axis=1)
no_attack_set_1 = np.take(no_attack_set_1_raw, [2,4,15], axis=1)
no_attack_set_2 = np.take(no_attack_set_2_raw, [2,4,15], axis=1)

# attack_set_1 = np.delete(attack_set_1_raw, 2, axis=1)
# attack_set_2 = np.delete(attack_set_2_raw, 2, axis=1)
# no_attack_set_1 = np.delete(no_attack_set_1_raw, 2, axis=1)
# no_attack_set_2 = np.delete(no_attack_set_2_raw, 2, axis=1)

'''
attack_set_1 = np.delete(attack_set_1, 2, axis=1)
attack_set_2 = np.delete(attack_set_2, 2, axis=1)
no_attack_set_1 = np.delete(no_attack_set_1, 2, axis=1)
no_attack_set_2 = np.delete(no_attack_set_2, 2, axis=1)

attack_set_1 = np.delete(attack_set_1, 2, axis=1)
attack_set_2 = np.delete(attack_set_2, 2, axis=1)
no_attack_set_1 = np.delete(no_attack_set_1, 2, axis=1)
no_attack_set_2 = np.delete(no_attack_set_2, 2, axis=1)
'''

'\nattack_set_1 = np.delete(attack_set_1, 2, axis=1)\nattack_set_2 = np.delete(attack_set_2, 2, axis=1)\nno_attack_set_1 = np.delete(no_attack_set_1, 2, axis=1)\nno_attack_set_2 = np.delete(no_attack_set_2, 2, axis=1)\n\nattack_set_1 = np.delete(attack_set_1, 2, axis=1)\nattack_set_2 = np.delete(attack_set_2, 2, axis=1)\nno_attack_set_1 = np.delete(no_attack_set_1, 2, axis=1)\nno_attack_set_2 = np.delete(no_attack_set_2, 2, axis=1)\n'

In [27]:
attack_set_1

array([[1.12374000e+05, 7.32020000e+04, 1.30292902e+01],
       [8.65600000e+04, 4.89820000e+04, 1.00103369e+01],
       [8.64750000e+04, 9.39960000e+04, 1.00104280e+01],
       [1.90464000e+05, 1.78417000e+05, 2.20925460e+01],
       [3.46089000e+05, 2.73224000e+05, 4.01689649e+01],
       [8.64420000e+04, 5.72520000e+04, 1.00026860e+01],
       [8.62750000e+04, 1.10852000e+05, 1.00074241e+01],
       [1.12371000e+05, 9.48340000e+04, 1.30279429e+01],
       [8.65950000e+04, 1.06914000e+05, 1.00103748e+01],
       [1.38181000e+05, 7.15900000e+04, 1.60248232e+01],
       [1.38418000e+05, 1.41103000e+05, 1.60456750e+01],
       [1.12547000e+05, 9.59720000e+04, 1.30279419e+01],
       [5.54064000e+05, 4.26032000e+05, 6.43268719e+01],
       [2.42291000e+05, 2.20102000e+05, 2.81108980e+01],
       [2.16224000e+05, 1.60968000e+05, 2.50938971e+01],
       [1.64381000e+05, 1.57162000e+05, 1.90538659e+01],
       [8.62830000e+04, 1.00748000e+05, 1.00103650e+01],
       [1.64235000e+05, 1.41618

In [28]:
zeroes_set = np.zeros((len(attack_set_1),1))
ones_set = np.ones((len(no_attack_set_1),1))

In [29]:
training_set = np.concatenate((attack_set_1,no_attack_set_1,no_attack_set_2), axis=0) 
training_targets = np.concatenate((ones_set, zeroes_set, zeroes_set), axis=0)

In [30]:
training_set

array([[1.12374000e+05, 7.32020000e+04, 1.30292902e+01],
       [8.65600000e+04, 4.89820000e+04, 1.00103369e+01],
       [8.64750000e+04, 9.39960000e+04, 1.00104280e+01],
       ...,
       [1.18310000e+04, 9.63080000e+04, 1.30225000e+01],
       [8.82000000e+03, 3.74820000e+04, 1.00095601e+01],
       [9.03900000e+03, 8.08840000e+04, 1.00102670e+01]])

In [31]:
training_set_standardized = tf.keras.utils.normalize(
    training_set,
    axis = -1,
    order = 2
)

In [36]:
input_size = 3
output_size = 1

model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation='relu', input_shape=(input_size,)),
    tf.keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.00001), 
                loss='binary_crossentropy', 
                metrics=['accuracy'])

In [38]:
model.fit(training_set, training_targets, epochs=300, verbose=1)

Train on 357 samples
Epoch 1/300
357/357 [==============================] - 0s 112us/sample - loss: 0.4714 - acc: 0.9720
Epoch 2/300
357/357 [==============================] - 0s 106us/sample - loss: 0.4710 - acc: 0.9720
Epoch 3/300
357/357 [==============================] - 0s 106us/sample - loss: 0.4685 - acc: 0.9720
Epoch 4/300
357/357 [==============================] - 0s 104us/sample - loss: 0.4667 - acc: 0.9720
Epoch 5/300
357/357 [==============================] - 0s 109us/sample - loss: 0.4637 - acc: 0.9720
Epoch 6/300
357/357 [==============================] - 0s 125us/sample - loss: 0.4623 - acc: 0.9720
Epoch 7/300
357/357 [==============================] - 0s 126us/sample - loss: 0.4602 - acc: 0.9720
Epoch 8/300
357/357 [==============================] - 0s 102us/sample - loss: 0.4590 - acc: 0.9720
Epoch 9/300
357/357 [==============================] - 0s 113us/sample - loss: 0.4573 - acc: 0.9720
Epoch 10/300
357/357 [==============================] - 0s 95us/sample - loss: 

357/357 [==============================] - 0s 117us/sample - loss: 0.3237 - acc: 0.9916
Epoch 83/300
357/357 [==============================] - 0s 120us/sample - loss: 0.3217 - acc: 0.9916
Epoch 84/300
357/357 [==============================] - 0s 107us/sample - loss: 0.3197 - acc: 0.9916
Epoch 85/300
357/357 [==============================] - 0s 116us/sample - loss: 0.3181 - acc: 0.9916
Epoch 86/300
357/357 [==============================] - 0s 110us/sample - loss: 0.3155 - acc: 0.9916
Epoch 87/300
357/357 [==============================] - 0s 108us/sample - loss: 0.3137 - acc: 0.9916
Epoch 88/300
357/357 [==============================] - 0s 119us/sample - loss: 0.3120 - acc: 0.9916
Epoch 89/300
357/357 [==============================] - 0s 124us/sample - loss: 0.3102 - acc: 0.9916
Epoch 90/300
357/357 [==============================] - 0s 127us/sample - loss: 0.3074 - acc: 0.9916
Epoch 91/300
357/357 [==============================] - 0s 104us/sample - loss: 0.3056 - acc: 0.9916
Epo

357/357 [==============================] - 0s 134us/sample - loss: 0.2636 - acc: 0.9888
Epoch 163/300
357/357 [==============================] - 0s 107us/sample - loss: 0.2660 - acc: 0.9916
Epoch 164/300
357/357 [==============================] - 0s 104us/sample - loss: 0.2638 - acc: 0.9916
Epoch 165/300
357/357 [==============================] - 0s 102us/sample - loss: 0.2599 - acc: 0.9916
Epoch 166/300
357/357 [==============================] - 0s 90us/sample - loss: 0.2582 - acc: 0.9916
Epoch 167/300
357/357 [==============================] - 0s 68us/sample - loss: 0.2576 - acc: 0.9916
Epoch 168/300
357/357 [==============================] - 0s 81us/sample - loss: 0.2569 - acc: 0.9916
Epoch 169/300
357/357 [==============================] - 0s 85us/sample - loss: 0.2647 - acc: 0.9888
Epoch 170/300
357/357 [==============================] - 0s 96us/sample - loss: 0.2622 - acc: 0.9916
Epoch 171/300
357/357 [==============================] - 0s 98us/sample - loss: 0.2588 - acc: 0.9916


357/357 [==============================] - 0s 128us/sample - loss: 0.2373 - acc: 0.9916
Epoch 243/300
357/357 [==============================] - 0s 109us/sample - loss: 0.2308 - acc: 0.9916
Epoch 244/300
357/357 [==============================] - 0s 100us/sample - loss: 0.2348 - acc: 0.9860
Epoch 245/300
357/357 [==============================] - 0s 99us/sample - loss: 0.2392 - acc: 0.9916
Epoch 246/300
357/357 [==============================] - 0s 100us/sample - loss: 0.2404 - acc: 0.9916
Epoch 247/300
357/357 [==============================] - 0s 114us/sample - loss: 0.2342 - acc: 0.9916
Epoch 248/300
357/357 [==============================] - 0s 87us/sample - loss: 0.2403 - acc: 0.9888
Epoch 249/300
357/357 [==============================] - 0s 92us/sample - loss: 0.2377 - acc: 0.9916
Epoch 250/300
357/357 [==============================] - 0s 91us/sample - loss: 0.2399 - acc: 0.9916
Epoch 251/300
357/357 [==============================] - 0s 90us/sample - loss: 0.2344 - acc: 0.9916

In [9]:
model.layers[0].get_weights()[1]

array([ 0.02230451, -0.0219545 ,  0.02230299, -0.02218401, -0.02362583,
        0.        , -0.02230149,  0.        ,  0.02230301,  0.        ,
        0.        , -0.02230111,  0.        ,  0.        ,  0.01525921,
        0.02230324, -0.01526081,  0.02230476,  0.02866562,  0.02230445,
        0.02547196,  0.01525899, -0.01526066,  0.02679703,  0.        ,
       -0.01501888,  0.0257307 , -0.02247812, -0.02230122,  0.        ,
        0.02230299,  0.02230295,  0.01525861,  0.        , -0.01528071,
       -0.02230123,  0.02230411,  0.02623801,  0.01525394,  0.02782579,
       -0.015261  ,  0.        ,  0.01516758,  0.0252851 ,  0.        ,
        0.        ,  0.01525773, -0.01399557,  0.        ,  0.01525919,
       -0.02383111, -0.02362276, -0.02370894,  0.        ,  0.01525934,
        0.02550788,  0.01525951, -0.01956817,  0.02230306,  0.01523943,
       -0.02230113, -0.02281268,  0.02559989,  0.        , -0.02230114,
        0.        , -0.02061267, -0.01526076,  0.        ,  0.  

In [10]:
attack_set_2_standardized = tf.keras.utils.normalize(
    attack_set_2,
    axis = -1,
    order = 2
)

In [11]:
model.predict(attack_set_1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [12]:
model.predict(attack_set_2)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [13]:
no_attack_set_2_standardized = tf.keras.utils.normalize(
    no_attack_set_2,
    axis = -1,
    order = 2
)

In [14]:
model.predict(no_attack_set_1)

array([[0.18081465],
       [0.1213873 ],
       [0.18399736],
       [0.1854757 ],
       [0.18081534],
       [0.12143421],
       [0.18081534],
       [0.12138712],
       [0.12138721],
       [0.1214743 ],
       [0.1070165 ],
       [0.12150076],
       [0.18094471],
       [0.12151212],
       [0.12154084],
       [0.12150216],
       [0.18081471],
       [0.12138712],
       [0.1213873 ],
       [0.18081588],
       [0.1213873 ],
       [0.12138712],
       [0.10695359],
       [0.1213873 ],
       [0.1213873 ],
       [0.18081418],
       [0.1213873 ],
       [0.12138712],
       [0.10695836],
       [0.12138712],
       [0.1069569 ],
       [0.12139261],
       [0.12149328],
       [0.12147614],
       [0.18081588],
       [0.12138712],
       [0.12138718],
       [0.18081465],
       [0.1213873 ],
       [0.12138712],
       [0.10695782],
       [0.06719202],
       [0.12138718],
       [0.18099648],
       [0.12138709],
       [0.12138677],
       [0.18081418],
       [0.121

In [15]:
model.predict(no_attack_set_2)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [17]:
model.save('my_model.h5')

In [20]:
model = tf.keras.models.load_model('my_model.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [23]:
model.predict([[1,1,1,1]])

ValueError: Error when checking input: expected dense_input to have shape (4,) but got array with shape (1,)